add 'markdown-it-task-checkbox' dependency to render checkboxes
nextcloud/notes pull request #787
Opened 2021-12-02 17:05 UTC by newhinton

fixes #325

this does not allow for using checkboxes from the markdown viewer. I would like to implement such a feature, but that probably requires a change in the upstream library.

2021-12-02 19:44 UTC, korelstar requested changes
Hey @newhinton , thank you very much for your contribution! I just want to request some very small changes.

2021-12-02 19:44 UTC, korelstar commented on src/components/EditorMarkdownIt.vue
> +			liClass: 'task-list-item'
```suggestion
			liClass: 'task-list-item',
```

2021-12-02 19:44 UTC, korelstar commented on src/components/EditorMarkdownIt.vue
> +			md
```suggestion
			md,
```

2021-12-02 19:44 UTC, korelstar commented on src/components/EditorMarkdownIt.vue
> +		}
```suggestion
		}
		label {
			cursor: default;
		}
```

2021-12-04 16:58 UTC, newhinton commented on src/components/EditorMarkdownIt.vue
> +		}
I think i did what you suggested

2021-12-05 13:30 UTC, korelstar approved these changes

2021-12-05 13:30 UTC, merged